---

- name: start php-fpm
  service: name=php-fpm enabled=yes state=started

- name: restart php-fpm
  service: name=php-fpm state=restarted
  register: result

- name: show result
  debug: msg={{ result.stdout_lines }}
