---

- name: Download Wordpress Farsi
  get_url: url=https://fa.wordpress.org/latest-fa_IR.tar.gz dest=/srv/latest-fa_IR.tar.gz

- name: Extract archive
  command: chdir=/srv/ /bin/tar xvf latest-fa_IR.tar.gz creates=/srv/wordpress

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/srv/wordpress/

- name: Fetch random salts For wordpress config
  local_action: command curl  https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no

- name: Create Wordpress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create Wordpress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

- name: Copy Wordpress config file
  template:
    src: wp-config.php
    dest: /srv/wordpress/

- name: Change ownership of Wordpress installation
  file:
    path: /srv/wordpress/
    owner: wordpress
    group: wordpress
    state: directory
    recurse: yes

- name: install SEManage
  yum: pkg=policycoreutils-python state=present

- name: set SeLinux policy for wordpress directory
  command: semanage fcontext -a -t httpd_sys_content_t "/srv/wordpress(/.*)?"

- name: set selinux policy for wp-config.php
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/wordpress/wp-config\.php"

- name: set selinux policy for  wp-content directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/wordpress/wp-content(/.*)?"

- name: set selinux policy for the *.php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/wordpress/.*\.php"

- name: set selinux policy for  the Upgarde directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/wordpress/wp-content/upgrade(/.*)?"

- name: set selinux policy for the uploads directory 
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/wordpress/wp-content/uploads(/.*)?"

- name: set selinux policy for the wp-includes php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/wordpress/wp-includes/.*\.php"

- name: set the Selinux on ll Files
  command: restorecon -Rv /srv/wordpress

- name: Start php-fpm Service
  service: name=php-fpm state=started enabled=yes

